Create nightOwl.java
MDdev0/Spigot-MafiaCraft pull request #1
Opened 2022-12-07 16:46 UTC by kalyus

2022-12-07 18:49 UTC, MDdev0 requested changes
Does not affect players who log in during the day. Also I like the isonline check, I should probably add it to all other calls to the player list.

2022-12-07 19:17 UTC, kalyus reviewed
Made the Daytime a range so it will apply the 200 tick effect repeatedly through the day.

2022-12-08 00:47 UTC, MDdev0 commented on src/mddev0/mafiacraft/abilities/nightOwl.java
> +        if (plugin.getServer().getWorlds().get(0).getTime() >= 1000 || worldTime <= 13000) { //At 7:00 AM through 7:00 PM
Recommend starting at 6:00 AM (0 ticks) per wiki definition, 7:00PM is correct

2022-12-11 02:46 UTC, MDdev0 approved these changes

2022-12-11 02:47 UTC, merged